services:
    datetime_normalizer:
        class: AppBundle\Normalizers\DateTimeNormalizer
        tags:
            - { name: serializer.normalizer }
    app.twig.extension.intl:
        class:        Twig_Extensions_Extension_Intl
        tags:
             - { name: 'twig.extension' }