services:
#    consumer.example:
#        class: ConsumerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    service_b:
        class: ConsumerBundle\Workers\ServiceB
        arguments: ["@serializer", "@doctrine.orm.entity_manager", "@logger"]